### ISSUE TITLE
./build.js script fails to run

### ISSUE THREAD

**Issue by NV** [montagejs/montagejs.org#43]
```
➤ ./build.js 

+ rm -rf /Users/nv/Code/montage/montagejs.org/tmp # in /Users/nv/Code/montage/montagejs.org/_build
+ mkdir /Users/nv/Code/montage/montagejs.org/tmp # in /Users/nv/Code/montage/montagejs.org/_build
+ git clone https://github.com/montagejs/popcorn.git /Users/nv/Code/montage/montagejs.org/tmp/popcorn # in /Users/nv/Code/montage/montagejs.org/_build
Cloning into '/Users/nv/Code/montage/montagejs.org/tmp/popcorn'...
remote: Counting objects: 263, done.
remote: Compressing objects: 100% (134/134), done.
remote: Total 263 (delta 127), reused 255 (delta 121)
Receiving objects: 100% (263/263), 321.67 KiB | 0 bytes/s, done.
Resolving deltas: 100% (127/127), done.
Checking connectivity... done
+ git checkout v0.12 # in /Users/nv/Code/montage/montagejs.org/tmp/popcorn
Branch v0.12 set up to track remote branch v0.12 from origin.
Switched to a new branch 'v0.12'
+ npm install # in /Users/nv/Code/montage/montagejs.org/tmp/popcorn
npm WARN package.json popcorn@0.0.2 No repository field.
npm http GET https://registry.npmjs.org/montage/0.12.4
npm http 304 https://registry.npmjs.org/montage/0.12.4
npm http GET https://registry.npmjs.org/collections
npm ERR! cb() never called!
npm ERR! not ok code 0

/Users/nv/Code/montage/montagejs.org/_build/node_modules/q/q.js:126
                    throw e;
                          ^
Error: npm install in /Users/nv/Code/montage/montagejs.org/tmp/popcorn exited with code 1
    at ChildProcess.<anonymous> (/Users/nv/Code/montage/montagejs.org/_build/build.js:32:29)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:789:12)
```

Any idea what’s going on?

**Comment by NV** [comment]
The following works well, no errors thrown:

```
➤ git clone git@github.com:montagejs/popcorn.git
➤ cd popcorn
➤ git checkout -b v0.12 origin/v0.12
➤ git pull --all
➤ npm install
```

**Comment by NV** [comment]
Problem somehow has been solved on itself. Probably one of the dependencies changed.

**Comment by NV** [comment]
This heisenbug still happens to me time to time. I have no idea why.

**Comment by NV** [comment]
http://stackoverflow.com/a/15483897/16185
